{% set name = "sqlite-fts4" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlite-fts4-{{ version }}.tar.gz
  sha256: 739a2faf696182e977d903a3376545de984cd0449a5c5d2cfc74ae5c018e415d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - sqlite_fts4
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/simonw/sqlite-fts4
  summary: Python functions for working with SQLite FTS4 search
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
